services:
  - type: web
    name: youtube-downloader-bot
    env: python
    plan: starter
    buildCommand: ""
    startCommand: "python main.py"
    envVars:
      - key: TOKEN
        sync: false
      - key: WEBHOOK_URL
        sync: false
