services:
  - type: web
    name: youtube-downloader-bot
    env: python
    plan: starter   # اگر آپ paid plan use کر رہے ہیں تو یہ لگائیں
    buildCommand: ""
    startCommand: "python main.py"
    envVars:
      - key: TOKEN
        sync: false
