services:
  - type: worker
    name: youtube-downloader-bot
    env: python
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    plan: free
    envVars:
      - key: TOKEN
        sync: false
